### ISSUE TITLE
# running testnet-node Evolution-Node

### ISSUE THREAD

**Issue by mshankarrao** [GlobalBoost/incentivized-testnet#1]
Email: evolution@xyz.com
Signal Username: evolution
Discord Username: evolution#6135
Testnode 1 name: Evolution-1
Testnode 2 name: [this is optional, as you can have at max two node running for a single user]
Tell us more about your skills and background that could be beneficial in future for Impact: Web-dev
What do you think could be good to implement in Impact Protocol: Dapps, Oracle, zK
Are you planning to build anything in Impact protocol in future: Yes

**Comment by peaceppp** [comment]
Email: jakartabans@gmail.com
Signal Username: jakartabans
Discord Username: 0xmonyaaa#2590
Testnode 1 name: Monyaaanode1
Testnode 2 name: monyaaanode2
Tell us more about your skills and background that could be beneficial in future for Impact: Web design
What do you think could be good to implement in Impact Protocol: zK
Are you planning to build anything in Impact protocol in future: Yes

**Comment by xnode9** [comment]
Email: ediprayitno8787@gmail.com
Signal Username: Edi Prayitno
Discord Username: edi#5879
Testnode 1 name: Evolution-1
Testnode 2 name: [this is optional, as you can have at max two node running for a single user]
Tell us more about your skills and background that could be beneficial in future for Impact: Web-dev
What do you think could be good to implement in Impact Protocol: Dapps, Oracle, zK
Are you planning to build anything in Impact protocol in future: Yes

**Comment by xnode9** [comment]
Email: ediprayitno8787@gmail.com
Signal Username: Edi Prayitno
Discord Username: edi#5879
Testnode 1 name: XNODE
Testnode 2 name: [this is optional, as you can have at max two node running for a single user]
Tell us more about your skills and background that could be beneficial in future for Impact: Web-dev
What do you think could be good to implement in Impact Protocol: Dapps, Oracle, zK
Are you planning to build anything in Impact protocol in future: Yes

**Comment by VadymU** [comment]
Email: vadim@vadimu.com
Signal Username: I have no signal
Discord Username: VadimU#3556
Testnode 1 name: Vadym
Testnode 2 name: VadymU
PublicKey: 0x123a63688e65740198b7e43643f9b990b0456d9532cc29222c2caf604aa35769
Tell us more about your skills and background that could be beneficial in future for Impact: I have run: Meson, Defund, Cascadia, Ziesha, Muon, Nolus, Celestia, Goracle, Transformers, Gear, OJO, Namada, Nibiru, Subspace, Starknet, Uptick, ChainFlip, Aleo, Wormholmes, Archway, Massa, Andromeda, Nolus, Fleek, elixir, SAOD. 
What do you think could be good to implement in Impact Protocol: zK, Daps
Are you planning to build anything in Impact protocol in future: I don't know yet

**Comment by mshankarrao** [comment]
> Email: [vadim@vadimu.com](mailto:vadim@vadimu.com)
> Signal Username: I have no signal
> Discord Username: VadimU#3556
> Testnode 1 name: Vadym
> Testnode 2 name: VadymU
> PublicKey: 0x123a63688e65740198b7e43643f9b990b0456d9532cc29222c2caf604aa35769
> Tell us more about your skills and background that could be beneficial in future for Impact: I have run: Meson, Defund, Cascadia, Ziesha, Muon, Nolus, Celestia, Goracle, Transformers, Gear, OJO, Namada, Nibiru, Subspace, Starknet, Uptick, ChainFlip, Aleo, Wormholmes, Archway, Massa, Andromeda, Nolus, Fleek, elixir, SAOD.
> What do you think could be good to implement in Impact Protocol: zK, Daps
> Are you planning to build anything in Impact protocol in future: I don't know yet

Hey @VadymU, please create a new issue instead and also Signal is mandatory as all the updates regarding the testnet goes there?

**Comment by pnpn1212** [comment]
Email: phuc.scizor@gmail.com
Signal Username: MFLow
Discord Username: MFLow#8823
Testnode 1 name: MFLow-VN1
Testnode 2 name: MFLow-VN2
PublicKey: 0xec10753aa12f4368e3b77138d0e51847be24fa5d7b06a852dae8ce5a0325ef59
Tell us more about your skills and background that could be beneficial in future for Impact: I have run: Base, Polygon-zk-evm, Subspace, Lamina1, Lens Protocol, Fleek, Wormholes, Elixir, Near, ETH, Cosmos, Avalanche, TON, APTOS, MINA
What do you think could be good to implement in Impact Protocol: zk, Dapps, Govenance
Are you planning to build anything in Impact protocol in future: I don't know yet

**Comment by mshankarrao** [comment]
> Email: [phuc.scizor@gmail.com](mailto:phuc.scizor@gmail.com)
> Signal Username: MFLow
> Discord Username: MFLow#8823
> Testnode 1 name: MFLow-VN1
> Testnode 2 name: MFLow-VN2
> PublicKey: 0xec10753aa12f4368e3b77138d0e51847be24fa5d7b06a852dae8ce5a0325ef59
> Tell us more about your skills and background that could be beneficial in future for Impact: I have run: Base, Polygon-zk-evm, Subspace, Lamina1, Lens Protocol, Fleek, Wormholes, Elixir, Near, ETH, Cosmos, Avalanche, TON, APTOS, MINA
> What do you think could be good to implement in Impact Protocol: zk, Dapps, Govenance
> Are you planning to build anything in Impact protocol in future: I don't know yet

Hey , can you create a separate issue instead of replying to existing issue.

**Comment by kopanathiharish** [comment]
Email: kopanathiharish@gmail.com
Signal Username: harris
Discord Username: Harish#3123
Testnode 1 name: Harris01

Tell us more about your skills and background that could be beneficial in future for Impact: dev
What do you think could be good to implement in Impact Protocol: Dapps, smart contract
Are you planning to build anything in Impact protocol in future: Yes

**Comment by mshankarrao** [comment]
> Email: [kopanathiharish@gmail.com](mailto:kopanathiharish@gmail.com) Signal Username: harris Discord Username: Harish#3123 Testnode 1 name: Harris01
> 
> Tell us more about your skills and background that could be beneficial in future for Impact: dev What do you think could be good to implement in Impact Protocol: Dapps, smart contract Are you planning to build anything in Impact protocol in future: Yes

Hey, please create a new issue and enter your information

**Comment by kopanathiharish** [comment]
> > Email: [kopanathiharish@gmail.com](mailto:kopanathiharish@gmail.com) Signal Username: harris Discord Username: Harish#3123 Testnode 1 name: Harris01
> > Tell us more about your skills and background that could be beneficial in future for Impact: dev What do you think could be good to implement in Impact Protocol: Dapps, smart contract Are you planning to build anything in Impact protocol in future: Yes
> 
> Hey, please create a new issue and enter your information

thankq

**Comment by mshankarrao** [comment]
> > > Email: [kopanathiharish@gmail.com](mailto:kopanathiharish@gmail.com) Signal Username: harris Discord Username: Harish#3123 Testnode 1 name: Harris01
> > > Tell us more about your skills and background that could be beneficial in future for Impact: dev What do you think could be good to implement in Impact Protocol: Dapps, smart contract Are you planning to build anything in Impact protocol in future: Yes
> > 
> > 
> > Hey, please create a new issue and enter your information
> 
> thankq

Sure no problem
