### ISSUE TITLE
running testnet-node mariakk

### ISSUE THREAD

**Issue by maria3121** [GlobalBoost/incentivized-testnet#40]
Email: marianacover12@gmail.com
Signal Username: mariakk
Discord Username: mariakk#3279
Testnode 1 name: mariakk1
Testnode 2 name: mariakk2
Tell us more about your skills and background that could be beneficial in future for Impact: Node runner testnet & Node Provider Mainnet
What do you think could be good to implement in Impact Protocol: Swaps, NFT
Are you planning to build anything in Impact protocol in future: yes

**Comment by nomad7617** [comment]
Hello, my second node was down mariakk2 https://prnt.sc/MPeCjIpW0uUO I already make it up agaian

**Comment by maria3121** [comment]
Hello, I have rebuild new impact on new server https://prnt.sc/MPeCjIpW0uUO
