### ISSUE TITLE
# running testnet-node NomadNode

### ISSUE THREAD

**Issue by nmdval** [GlobalBoost/incentivized-testnet#7]
Email: nomad@nomad-node.com
Signal Username: nomad
Discord Username: nomad#7617
Testnode 1 name: NomadUp1
Testnode 2 name: NomadUp2
Tell us more about your skills and background that could be beneficial in future for Impact: Node Validator & Staking Provider
What do you think could be good to implement in Impact Protocol: Swap, Bridge, Staking
Are you planning to build anything in Impact protocol in future: Y

**Comment by nomadvalidator** [comment]
Hello, today 3/6/2023 my second node **NomadUp2** out of billing then move to new server. https://prnt.sc/VfqWcZOlrQcO

**Comment by nomadvalidator** [comment]
Hello, my second node down but its up now https://prnt.sc/2YPbzI2kN8Qh
