### ISSUE TITLE
Vadym's node

### ISSUE THREAD

**Issue by VadymU** [GlobalBoost/incentivized-testnet#71]
Email: vadim@vadimu.com
Signal Username: +380503863019
Discord Username: VadimU#3556
Testnode 1 name: Vadym
Testnode 2 name: VadymU
PublicKey: 0x123a63688e65740198b7e43643f9b990b0456d9532cc29222c2caf604aa35769
Tell us more about your skills and background that could be beneficial in future for Impact: I have run: Meson, Defund, Cascadia, Ziesha, Muon, Nolus, Celestia, Goracle, Transformers, Gear, OJO, Namada, Nibiru, Subspace, Starknet, Uptick, ChainFlip, Aleo, Wormholmes, Archway, Massa, Andromeda, Nolus, Fleek, elixir, SAOD.
What do you think could be good to implement in Impact Protocol: zK, Daps
Are you planning to build anything in Impact protocol in future: I don't know yet

**Comment by mshankarrao** [comment]
> Email: [vadim@vadimu.com](mailto:vadim@vadimu.com)
> Signal Username: [+380503863019](tel:+380503863019)
> Discord Username: VadimU#3556
> Testnode 1 name: Vadym
> Testnode 2 name: VadymU
> PublicKey: 0x123a63688e65740198b7e43643f9b990b0456d9532cc29222c2caf604aa35769
> Tell us more about your skills and background that could be beneficial in future for Impact: I have run: Meson, Defund, Cascadia, Ziesha, Muon, Nolus, Celestia, Goracle, Transformers, Gear, OJO, Namada, Nibiru, Subspace, Starknet, Uptick, ChainFlip, Aleo, Wormholmes, Archway, Massa, Andromeda, Nolus, Fleek, elixir, SAOD.
> What do you think could be good to implement in Impact Protocol: zK, Daps
> Are you planning to build anything in Impact protocol in future: I don't know yet

Join this group for testnet updates
https://signal.group/#CjQKICa9F2r95FQoGhYjc02lwNgKZCOfDEZngfoWgr_ZkHc4EhAOywghKv4DebEkPsicSCFb
