### ISSUE TITLE
# running impact-testnet-node IndKop1 and IndKop2

### ISSUE THREAD

**Issue by Indkop** [GlobalBoost/incentivized-testnet#77]
Email: indirakop25@gmail.com
Signal Username: indkop
Discord Username:indkop#8373
Testnode 1 name: IndKop1
Testnode 2 name: IndKop2
Tell us more about your skills and background that could be beneficial in future for Impact: Community moderator, Node Runner
What do you think could be good to implement in Impact Protocol: dApps, ZK, etc
Are you planning to build anything in Impact protocol in future: Yeah may be some apps related to ZK

**Comment by mshankarrao** [comment]
> Email: [indirakop25@gmail.com](mailto:indirakop25@gmail.com)
> Signal Username:
> Discord Username:
> Testnode 1 name: IndKop1
> Testnode 2 name: IndKop2
> Tell us more about your skills and background that could be beneficial in future for Impact: Community moderator, Node Runner
> What do you think could be good to implement in Impact Protocol: dApps, ZK, etc
> Are you planning to build anything in Impact protocol in future: Yeah may be some apps related to ZK

Hey Indkop, thanks for joining, could you please update your signal and discord username. Signal is mandatory as you will get all the updates about testnet in our signal group. Please join the link below 
https://signal.group/#CjQKICa9F2r95FQoGhYjc02lwNgKZCOfDEZngfoWgr_ZkHc4EhAOywghKv4DebEkPsicSCFb

**Comment by Indkop** [comment]
My server will be unavailable for a few days while I reschedule it for the upcoming phase.
