### ISSUE TITLE
# running impact betanet node -geet01 and geet02

### ISSUE THREAD

**Issue by geetaagrawal25** [GlobalBoost/incentivized-testnet#78]
Email: mgeetanjali25@gmail.com
Signal Username: geet
Discord Username: geeta_rao_agrawal#4352
Testnode 1 name: Geet01
Testnode 2 name: Geet02
Tell us more about your skills and background that could be beneficial in future for Impact: Experience Smart contract developer in various blockchains
What do you think could be good to implement in Impact Protocol: A lot of dapps can be ported to this hybrid chain
Are you planning to build anything in Impact protocol in the future: yes, I have several ideas and will building a lot of dApps

**Comment by mshankarrao** [comment]
> Email: [mgeetanjali25@gmail.com](mailto:mgeetanjali25@gmail.com)
> Signal Username:
> Discord Username: geeta_rao_agrawal#4352
> Testnode 1 name: Geet01
> Testnode 2 name: Geet02
> Tell us more about your skills and background that could be beneficial in future for Impact: Experience Smart contract developer in various blockchains
> What do you think could be good to implement in Impact Protocol: A lot of dapps can be ported to this hybrid chain
> Are you planning to build anything in Impact protocol in the future: yes, I have several ideas and will building a lot of dApps

Hey @geetaagrawal25 could you please provide your signal username and join our beta testnet group. Below is the link 
https://signal.group/#CjQKICa9F2r95FQoGhYjc02lwNgKZCOfDEZngfoWgr_ZkHc4EhAOywghKv4DebEkPsicSCFb

**Comment by geetaagrawal25** [comment]
> > Email: [mgeetanjali25@gmail.com](mailto:mgeetanjali25@gmail.com)
> > Signal Username:
> > Discord Username: geeta_rao_agrawal#4352
> > Testnode 1 name: Geet01
> > Testnode 2 name: Geet02
> > Tell us more about your skills and background that could be beneficial in future for Impact: Experience Smart contract developer in various blockchains
> > What do you think could be good to implement in Impact Protocol: A lot of dapps can be ported to this hybrid chain
> > Are you planning to build anything in Impact protocol in the future: yes, I have several ideas and will building a lot of dApps
> 
> Hey @geetaagrawal25 could you please provide your signal username and join our beta testnet group. Below is the link https://signal.group/#CjQKICa9F2r95FQoGhYjc02lwNgKZCOfDEZngfoWgr_ZkHc4EhAOywghKv4DebEkPsicSCFb

updated, thank you much

**Comment by mshankarrao** [comment]
> > > Email: [mgeetanjali25@gmail.com](mailto:mgeetanjali25@gmail.com)
> > > Signal Username:
> > > Discord Username: geeta_rao_agrawal#4352
> > > Testnode 1 name: Geet01
> > > Testnode 2 name: Geet02
> > > Tell us more about your skills and background that could be beneficial in future for Impact: Experience Smart contract developer in various blockchains
> > > What do you think could be good to implement in Impact Protocol: A lot of dapps can be ported to this hybrid chain
> > > Are you planning to build anything in Impact protocol in the future: yes, I have several ideas and will building a lot of dApps
> > 
> > 
> > Hey @geetaagrawal25 could you please provide your signal username and join our beta testnet group. Below is the link https://signal.group/#CjQKICa9F2r95FQoGhYjc02lwNgKZCOfDEZngfoWgr_ZkHc4EhAOywghKv4DebEkPsicSCFb
> 
> updated, thank you much

Sure no problem. Thanks for updating the signal username

**Comment by geetaagrawal25** [comment]
**Due to billing issues, nodes got stopped.**
